apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-inference-service
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: inference-service
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - ports:
        - protocol: TCP
          port: 8000
  egress:
    - ports:
        - protocol: TCP
          port: 5000
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 5432
        - protocol: UDP
          port: 53
