apiVersion: apps/v1
kind: Deployment
metadata:
  name: inference-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inference-service
  template:
    metadata:
      labels:
        app: inference-service
    spec:
      containers:
        - name: inference
          image: 352126234584.dkr.ecr.ap-south-1.amazonaws.com/nexus-mlops-inference:d8445249d8485f5962b47640944ecd21cc93fafd
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: MLFLOW_TRACKING_URI
              value: http://mlflow.mlflow.svc.cluster.local:5000
            - name: MLFLOW_RUN_ID
              value: "eb39ea731f1f4e45a8e9185c229a402d"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 15
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: inference-service
  namespace: default
spec:
  selector:
    app: inference-service
  ports:
    - port: 8000
      targetPort: 8000
